#!/bin/bash

set -e

## Build binaries
build() {
    cd src
    rm -rf venv
    FILES=$(ls *.requirements)
    python3 -m venv venv
    source venv/bin/activate
    pip install shiv
    for FILE in $FILES; do
        BASENAME="${FILE%%.*}"
        if [[ -f "$BASENAME.py" ]]; then
            mkdir tmp
            cp $BASENAME.py tmp/main.py
            shiv -o ../$BASENAME -p "/usr/bin/env python3" -r $BASENAME.requirements -e main:run --site-packages tmp
            rm -rf tmp
        else
            shiv -o ../$BASENAME -p "/usr/bin/env python3" -r $BASENAME.requirements -c $BASENAME
        fi
    done
    rm -rf venv
}

## Show this help message
help() {
    # ANSI Colors
    RED='\033[31m'
    GREEN='\033[32m'
    YELLOW='\033[33m'
    CYAN='\033[36m'
    WHITE='\033[37m'
    RESET='\033[0m'

    # Usage
    printf "${CYAN}Usage: $0 [command]${RESET}\n\n"
    printf "${CYAN}Commands:${RESET}\n"

    awk -v YELLOW="$YELLOW" -v RESET="$RESET" '
        /^##/ {
            desc = substr($0, 4);
            getline;
            if ($0 ~ /\(\)/) {
                method = $1;
                gsub(/\(\)/, "", method);
                printf "  %s%-20s%s %s\n", YELLOW, method, RESET, desc;
            }
        }
    ' "$0"
}

# Main
if [[ $# -lt 1 ]]; then
    help
else
    "$@"
fi
